-- MySQL Script generated by MySQL Workbench
-- Wed Jan 30 20:53:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inf1013` DEFAULT CHARACTER SET utf8 ;
USE `inf1013` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inf1013`.`product` (
  `product_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`clothe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inf1013`.`clothe` (
  `clothe_id` INT NOT NULL,
  `size` ENUM('small', 'medium', 'large') NOT NULL,
  `color` ENUM('red', 'blue', 'white', 'black', 'yellow') NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `product_product_id` INT(11) NOT NULL,
  PRIMARY KEY (`clothe_id`, `product_product_id`),
  INDEX `fk_clothe_product_idx` (`product_product_id` ASC),
  CONSTRAINT `fk_clothe_product`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `inf1013`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inf1013`.`ware` (
  `ware_id` INT NOT NULL,
  `weight` DECIMAL(10,2) NULL,
  `height` DECIMAL(10,2) NULL,
  `width` DECIMAL(10,2) NULL,
  `depth` DECIMAL(10,2) NULL,
  `product_product_id` INT(11) NOT NULL,
  PRIMARY KEY (`ware_id`, `product_product_id`),
  INDEX `fk_ware_product1_idx` (`product_product_id` ASC),
  CONSTRAINT `fk_ware_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `inf1013`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
